services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    volumes:
      - "./backend:/backend"
    command: ["sh", "-c", "python manage.py collectstatic --noinput && DJANGO_SETTINGS_MODULE=lctec_project.dev_settings python manage.py runserver 0.0.0.0:8000"]    
    networks:
      - "backend"

networks:
  backend:
    driver: bridge